[package]
name = "otd-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
otd-chop = { version = "0.1.0", path = "../otd-chop" }
otd-core = { version = "0.1.0", path = "../otd-core" }
otd-dat = { version = "0.1.0", path = "../otd-dat" }
otd-gpu = { version = "0.1.0", path = "../otd-gpu" }
otd-py = { version = "0.1.0", path = "../otd-py" }

[dev-dependencies]
image = { version = "0.25.9", default-features = false, features = ["png"] }
wgpu = "29"
