//! The shipped `examples/*.otd` files are generated, not hand-saved.
//!
//! Same argument as the operator reference: a committed artefact that has to
//! be regenerated by remembering to regenerate it will one day describe a
//! patch that no longer exists. `otd demo <name> --out <file>` writes them,
//! and this fails the build when a committed one has drifted from the demo it
//! came from.

use std::path::{Path, PathBuf};
use std::process::Command;

fn binary() -> PathBuf {
    // The test binary lives next to the one being tested.
    let mut path = std::env::current_exe().unwrap();
    path.pop();
    if path.ends_with("deps") {
        path.pop();
    }
    path.join(format!("otd{}", std::env::consts::EXE_SUFFIX))
}

fn examples() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../examples")
}

fn scratch() -> PathBuf {
    let dir = std::env::temp_dir().join(format!("otd-examples-{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    dir
}

#[test]
fn every_committed_example_matches_the_demo_it_came_from() {
    let dir = scratch();
    let mut checked = 0;

    for name in otd_engine::demo::NAMES {
        let committed = examples().join(format!("{name}.otd"));
        if !committed.exists() {
            // Not every demo is shipped as a file; the ones that are must be
            // right.
            continue;
        }
        let regenerated = dir.join(format!("{name}.otd"));
        let out = Command::new(binary())
            .args(["demo", name, "--out"])
            .arg(&regenerated)
            .output()
            .expect("run otd");
        assert!(
            out.status.success(),
            "otd demo {name}: {}",
            String::from_utf8_lossy(&out.stderr)
        );

        let want = std::fs::read_to_string(&committed).unwrap();
        let got = std::fs::read_to_string(&regenerated).unwrap();
        let differing = want
            .lines()
            .zip(got.lines())
            .filter(|(a, b)| a != b)
            .count()
            + want.lines().count().abs_diff(got.lines().count());
        assert_eq!(
            want, got,
            "examples/{name}.otd is {differing} line(s) out of date. Run:\n\n    \
             cargo run -p otd-cli -- demo {name} --out examples/{name}.otd\n"
        );
        checked += 1;
    }

    assert!(checked >= 5, "only {checked} examples checked");
    std::fs::remove_dir_all(&dir).ok();
}

#[test]
fn an_unknown_demo_name_lists_the_real_ones() {
    let out = Command::new(binary())
        .args(["demo", "nonsuch", "--out", "/tmp/otd-nonsuch.otd"])
        .output()
        .expect("run otd");
    assert!(!out.status.success());
    let message = String::from_utf8_lossy(&out.stderr);
    assert!(message.contains("nonsuch"), "{message}");
    // Being told what you could have typed is the whole value of the error.
    assert!(message.contains("starter"), "{message}");
}

#[test]
fn demo_without_an_output_says_what_is_missing() {
    let out = Command::new(binary())
        .args(["demo", "starter"])
        .output()
        .expect("run otd");
    assert!(!out.status.success());
    assert!(
        String::from_utf8_lossy(&out.stderr).contains("--out"),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
}
