[package]
name = "otd-gpu"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
bytemuck = { version = "1.25.2", features = ["derive"] }
log = "0.4.33"
otd-core = { version = "0.1.0", path = "../otd-core" }
pollster = "1.0.1"
slotmap = "1.1.1"
thiserror = "2.0.19"
wgpu = "29"

[dev-dependencies]
image = { version = "0.25.10", default-features = false, features = ["png"] }
