[package]
name = "otd-app"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
eframe = { version = "0.35.0", features = ["wgpu"] }
egui = "0.35.0"
env_logger = "0.11.11"
log = "0.4.33"
otd-chop = { version = "0.1.0", path = "../otd-chop" }
otd-core = { version = "0.1.0", path = "../otd-core" }
otd-dat = { version = "0.1.0", path = "../otd-dat" }
otd-engine = { version = "0.1.0", path = "../otd-engine" }
otd-ai = { version = "0.1.0", path = "../otd-ai" }
otd-gpu = { version = "0.1.0", path = "../otd-gpu" }
rfd = "0.17.2"
wgpu = "29"
